/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.server.form;

import java.io.IOException;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import rs.ac.bg.fon.silab.jdbc.example1.components.table.model.RadnikTableModel;
import rs.ac.bg.fon.silab.jdbc.example1.db.DatabaseRepository;
import rs.ac.bg.fon.silab.jdbc.example1.domen.IDomainEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.KupacEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.RadnikEntity;
import rs.ac.bg.fon.silab.server.thread.NitOsveziUlogovaneRadnike;
import rs.ac.bg.fon.silab.server.thread.ThreadClient;
import rs.ac.bg.fon.silab.server.thread.ThreadServer;

/**
 *
 * @author FON
 */
public class FServer extends javax.swing.JFrame {

    /**
     * Creates new form FServer
     */
    public FServer() {
        initComponents();
        jBtnStopServer.setEnabled(false);
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnStartServer = new javax.swing.JButton();
        jBtnStopServer = new javax.swing.JButton();
        jLblClock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUlogovaniRadnici = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnStartServer.setText("Pokrenite server");
        jBtnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartServerActionPerformed(evt);
            }
        });

        jBtnStopServer.setText("Zaustavite server");
        jBtnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStopServerActionPerformed(evt);
            }
        });

        jLblClock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTableUlogovaniRadnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableUlogovaniRadnici);

        jLabel1.setText("Prikaz ulogovanih radnika:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnStartServer)
                        .addComponent(jBtnStopServer)))
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartServerActionPerformed
        if(server == null || !server.isAlive()){
            try {
                server = new ThreadServer(9009);
                server.start();
                jBtnStartServer.setEnabled(false);
                jBtnStopServer.setEnabled(true);
                NitOsveziUlogovaneRadnike nit = new NitOsveziUlogovaneRadnike(this);
                nit.start();
                jPanel1.setVisible(true);
//                JOptionPane.showMessageDialog(this, "Server je pokrenut");
            } catch (IOException ex) {
                Logger.getLogger(FServer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Server je vec pokrenut");
        }
    }//GEN-LAST:event_jBtnStartServerActionPerformed

    private void jBtnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStopServerActionPerformed
        
        if(server.getUlogovaniRadnici().isEmpty()){
            server.interrupt();
            jBtnStartServer.setEnabled(true);
            jBtnStopServer.setEnabled(false);
            jPanel1.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Ne mozete da ugasite server zato sto su "+ server.getUlogovaniRadnici().size()+"klijenata povezana na server!");
            return;
        }
    }//GEN-LAST:event_jBtnStopServerActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnStartServer;
    private javax.swing.JButton jBtnStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblClock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUlogovaniRadnici;
    // End of variables declaration//GEN-END:variables
    private ThreadServer server;

//    public void postaviModelUlogovanihRadnika() {
//        try {
//            List<RadnikEntity> radniciLista=new ArrayList<>();
////            List<IDomainEntity> radnici = new DatabaseRepository().vratiSve(new KupacEntity());
//            for (ThreadClient client : server.vratiKonektovane()) {
//                radniciLista.add(client.getRadnik());
//            }
//            TableModel tm = new RadnikTableModel(radniciLista);
//            jTableUlogovaniRadnici.setModel(tm);
//        } catch (Exception ex) {
//            Logger.getLogger(FServer.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    private void tabela() {
        RadnikTableModel model = new RadnikTableModel();
        jTableUlogovaniRadnici.setModel(model);
    }

    public JTable getTabela() {
        return jTableUlogovaniRadnici;
    }

    public void odjavi(RadnikEntity r) {
        RadnikTableModel model = (RadnikTableModel) jTableUlogovaniRadnici.getModel();
        model.odjavi(r);
    }
    
}
